import { StyleSheet, Dimensions } from "react-native"

const { width, height } = Dimensions.get("window")

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1e1e1e",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },
  scrollContent: {
    padding: 16,
    paddingTop: 8,
  },
  header: {
    marginBottom: 20,
    paddingTop: 8,
  },
  greeting: {
    fontSize: Math.min(28, width * 0.07),
    color: "#fff",
    fontWeight: "700",
    marginBottom: 4,
    lineHeight: Math.min(34, width * 0.085),
  },
  name: {
    fontWeight: "bold",
    color: "#f3631a",
  },
  subtitle: {
    fontSize: Math.min(16, width * 0.04),
    color: "#aaa",
    lineHeight: Math.min(20, width * 0.05),
  },
  weatherSection: {
    backgroundColor: "#2a2a2a",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  weatherMain: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  weatherIconLarge: {
    fontSize: Math.min(36, width * 0.09),
    marginRight: 16,
  },
  weatherInfo: {
    flex: 1,
  },
  weatherTempLarge: {
    fontSize: Math.min(28, width * 0.07),
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 2,
  },
  weatherConditionLarge: {
    fontSize: Math.min(16, width * 0.04),
    color: "#fff",
    fontWeight: "600",
  },
  weatherDetails: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#444",
  },
  weatherDetailItem: {
    alignItems: "center",
    flex: 1,
  },
  weatherDetailIcon: {
    fontSize: 16,
    marginBottom: 2,
  },
  weatherDetailLabel: {
    fontSize: 10,
    color: "#aaa",
    marginBottom: 2,
  },
  weatherDetailValue: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 8,
  },
  statCard: {
    backgroundColor: "#2a2a2a",
    borderRadius: 12,
    padding: 16,
    flex: 1,
    borderLeftWidth: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    minHeight: 80,
  },
  statValue: {
    fontSize: Math.min(24, width * 0.06),
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  statTitle: {
    fontSize: Math.min(12, width * 0.03),
    color: "#aaa",
    fontWeight: "600",
  },
  statSubtitle: {
    fontSize: Math.min(10, width * 0.025),
    color: "#666",
    marginTop: 2,
  },
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: Math.min(20, width * 0.05),
    fontWeight: "bold",
    color: "#fff",
  },
  markAllReadButton: {
    backgroundColor: "#f3631a",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  markAllReadText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  notificationCard: {
    backgroundColor: "#2a2a2a",
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "flex-start",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  notificationCardUnread: {
    borderLeftWidth: 4,
    borderLeftColor: "#f3631a",
    backgroundColor: "#2d2d2d",
  },
  notificationIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f3631a",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  notificationIconText: {
    fontSize: 16,
  },
  notificationContent: {
    flex: 1,
  },
  notificationTitle: {
    color: "#fff",
    fontSize: Math.min(16, width * 0.04),
    fontWeight: "600",
    marginBottom: 4,
  },
  notificationText: {
    color: "#aaa",
    fontSize: Math.min(14, width * 0.035),
    lineHeight: Math.min(18, width * 0.045),
    marginBottom: 4,
  },
  notificationTime: {
    color: "#666",
    fontSize: Math.min(12, width * 0.03),
  },
  notificationIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#f3631a",
    marginLeft: 12,
    marginTop: 4,
  },
  viewAllButton: {
    backgroundColor: "#2a2a2a",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#444",
    marginTop: 8,
  },
  viewAllText: {
    color: "#f3631a",
    fontSize: Math.min(14, width * 0.035),
    fontWeight: "600",
  },
  rideCard: {
    backgroundColor: "#2a2a2a",
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  rideInfo: {
    flex: 1,
  },
  rideDestination: {
    color: "#fff",
    fontSize: Math.min(16, width * 0.04),
    fontWeight: "600",
    marginBottom: 4,
  },
  ridePack: {
    color: "#aaa",
    fontSize: Math.min(14, width * 0.035),
  },
  rideTime: {
    alignItems: "center",
    flexDirection: "row",
  },
  rideTimeText: {
    color: "#f3631a",
    fontSize: Math.min(16, width * 0.04),
    fontWeight: "bold",
    marginRight: 8,
  },
  rideArrow: {
    color: "#f3631a",
    fontSize: 18,
    fontWeight: "bold",
  },
  emptyState: {
    backgroundColor: "#2a2a2a",
    borderRadius: 12,
    padding: 24,
    alignItems: "center",
    borderStyle: "dashed",
    borderWidth: 2,
    borderColor: "#444",
  },
  emptyStateIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  emptyStateText: {
    color: "#fff",
    fontSize: Math.min(16, width * 0.04),
    fontWeight: "600",
    marginBottom: 4,
  },
  emptyStateSubtext: {
    color: "#aaa",
    fontSize: Math.min(14, width * 0.035),
  },
  activityItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  activityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#f3631a",
    marginRight: 16,
  },
  activityContent: {
    flex: 1,
  },
  activityText: {
    color: "#fff",
    fontSize: Math.min(14, width * 0.035),
    marginBottom: 2,
  },
  activityAction: {
    fontWeight: "600",
  },
  activityPack: {
    color: "#f3631a",
    fontWeight: "600",
  },
  activityTime: {
    color: "#aaa",
    fontSize: Math.min(12, width * 0.03),
  },
  bottomSpacing: {
    height: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContainer: {
    backgroundColor: "#2a2a2a",
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: Math.min(320, width * 0.9),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: Math.min(18, width * 0.045),
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 8,
    textAlign: "center",
  },
  modalMessage: {
    fontSize: Math.min(14, width * 0.035),
    color: "#aaa",
    marginBottom: 24,
    textAlign: "center",
    lineHeight: Math.min(20, width * 0.05),
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  modalButtonPrimary: {
    backgroundColor: "#f3631a",
  },
  modalButtonSecondary: {
    backgroundColor: "#444",
  },
  modalButtonDestructive: {
    backgroundColor: "#dc3545",
  },
  modalButtonText: {
    fontSize: Math.min(14, width * 0.035),
    fontWeight: "600",
    color: "#fff",
  },
})
