import { StyleSheet } from "react-native"
import { PRIMARY_APP_COLOR } from "../config"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
  },
  statusBarFill: {
    backgroundColor: "#1a1a1a", // Same as header background
    width: "100%",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1a1a1a",
    paddingVertical: 16,
    paddingHorizontal: 16,
    minHeight: 56,
    borderBottomWidth: 1,
    borderBottomColor: "#2a2a2a",
  },
  headerTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 16,
  },
  backButton: {
    padding: 8,
    borderRadius: 20,
    minWidth: 40,
    alignItems: "center",
  },
  infoButton: {
    padding: 8,
    borderRadius: 20,
    minWidth: 40,
    alignItems: "center",
  },
  chatContainer: {
    flex: 1,
    backgroundColor: "#121212",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#121212",
  },
  loadingText: {
    color: "#fff",
    marginTop: 12,
    fontSize: 16,
  },
  messagesList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  messagesContent: {
    paddingTop: 16,
    paddingBottom: 8,
  },
  messageContainer: {
    marginBottom: 16,
    alignItems: "flex-start",
  },
  ownMessageContainer: {
    alignItems: "flex-end",
  },
  messageBubble: {
    backgroundColor: "#2a2a2a",
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    maxWidth: "80%",
  },
  ownMessageBubble: {
    backgroundColor: PRIMARY_APP_COLOR,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 4,
  },
  senderName: {
    color: "#ccc",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 4,
  },
  messageText: {
    color: "#fff",
    fontSize: 16,
    lineHeight: 22,
  },
  ownMessageText: {
    color: "#fff",
  },
  messageTime: {
    color: "#999",
    fontSize: 12,
    marginTop: 4,
    alignSelf: "flex-end",
  },
  ownMessageTime: {
    color: "rgba(255, 255, 255, 0.7)",
  },
  systemMessage: {
    alignItems: "center",
    marginVertical: 12,
  },
  systemMessageText: {
    color: "#999",
    fontSize: 14,
    fontStyle: "italic",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#2a2a2a",
    backgroundColor: "#1a1a1a",
  },
  messageInput: {
    flex: 1,
    backgroundColor: "#2a2a2a",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 12,
    color: "#fff",
    fontSize: 16,
    maxHeight: 120,
    minHeight: 40,
    marginRight: 12,
  },
  sendButton: {
    backgroundColor: PRIMARY_APP_COLOR,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: PRIMARY_APP_COLOR,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  sendButtonDisabled: {
    backgroundColor: "#666",
    shadowOpacity: 0,
    elevation: 0,
  },
  messagesContainer: {
    backgroundColor: "#121212",
    paddingHorizontal: 4,
  },
  inputToolbar: {
    backgroundColor: "#1a1a1a",
    borderTopWidth: 1,
    borderTopColor: "#2a2a2a",
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 72,
  },
  inputPrimary: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingBottom: 4,
  },
  textInput: {
    backgroundColor: "#2a2a2a",
    borderRadius: 24,
    borderWidth: 0,
    color: "#fff",
    fontSize: 16,
    lineHeight: 20,
    marginHorizontal: 8,
    paddingHorizontal: 18,
    paddingVertical: 14,
    paddingTop: 14,
    minHeight: 48,
    maxHeight: 120,
  },
  sendContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: 4,
    marginBottom: 6,
  },
  typingContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#121212",
  },
  typingBubble: {
    backgroundColor: "#2a2a2a",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  typingText: {
    color: "#666",
    fontSize: 14,
    marginRight: 8,
  },
  typingDots: {
    flexDirection: "row",
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#666",
    marginHorizontal: 1,
  },
  dot1: {
    opacity: 0.4,
  },
  dot2: {
    opacity: 0.7,
  },
  dot3: {
    opacity: 1,
  },
  rightMessageWrapper: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginRight: 8,
    marginVertical: 2,
  },
  replyContainer: {
    backgroundColor: "#2a2a2a",
    borderTopWidth: 1,
    borderTopColor: "#3a3a3a",
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  replyContent: {
    flex: 1,
    marginRight: 12,
  },
  replyLabel: {
    color: PRIMARY_APP_COLOR,
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 2,
  },
  replyText: {
    color: "#ccc",
    fontSize: 14,
  },
  cancelReplyButton: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: "#3a3a3a",
    minWidth: 32,
    alignItems: "center",
  },
  cancelReplyText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: "#ff4444",
    fontSize: 16,
    textAlign: "center",
  },
})
