import { StyleSheet } from "react-native"
import { PRIMARY_APP_COLOR } from "../config"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1e1e1e",
  },
  statusBarFill: {
    backgroundColor: "#1a1a1a",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#1a1a1a",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  headerTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 16,
  },
  content: {
    flex: 1,
    backgroundColor: "#1e1e1e",
  },
  packImageContainer: {
    alignItems: "center",
    paddingVertical: 24,
    backgroundColor: "#1e1e1e",
  },
  packImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  packImagePlaceholder: {
    backgroundColor: PRIMARY_APP_COLOR,
    justifyContent: "center",
    alignItems: "center",
  },
  packImageText: {
    color: "white",
    fontSize: 48,
    fontWeight: "bold",
  },
  packDetails: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  packName: {
    color: "white",
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 12,
  },
  packMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    marginBottom: 16,
  },
  memberCount: {
    color: "#aaa",
    fontSize: 16,
    marginRight: 12,
  },
  publicBadge: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
  },
  publicBadgeText: {
    color: "white",
    fontSize: 12,
    fontWeight: "500",
  },
  chatBadge: {
    backgroundColor: PRIMARY_APP_COLOR,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  chatBadgeText: {
    color: "white",
    fontSize: 12,
    fontWeight: "500",
  },
  description: {
    color: "#ccc",
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
    marginBottom: 16,
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  tagBadge: {
    backgroundColor: "#333",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    margin: 4,
  },
  tagText: {
    color: "#ccc",
    fontSize: 14,
  },
  actionButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    paddingBottom: 24,
    justifyContent: "space-around",
  },
  actionButton: {
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    minWidth: 80,
  },
  actionButtonText: {
    color: "white",
    fontSize: 14,
    marginTop: 4,
    textAlign: "center",
  },
  routesSection: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  sectionTitle: {
    color: "white",
    fontSize: 20,
    fontWeight: "600",
  },
  addRouteButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PRIMARY_APP_COLOR,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  addRouteButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 4,
  },
  routeCard: {
    backgroundColor: "#2a2a2a",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  routeName: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  routeDetail: {
    color: "#aaa",
    fontSize: 14,
    marginBottom: 8,
  },
  routeDistance: {
    color: PRIMARY_APP_COLOR,
    fontSize: 14,
    fontWeight: "500",
  },
  emptyRoutes: {
    alignItems: "center",
    paddingVertical: 40,
  },
  emptyRoutesText: {
    color: "#aaa",
    fontSize: 18,
    fontWeight: "500",
    marginTop: 12,
    marginBottom: 8,
  },
  emptyRoutesSubtext: {
    color: "#666",
    fontSize: 14,
    textAlign: "center",
    paddingHorizontal: 20,
  },
  // Modal styles
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  menuContainer: {
    backgroundColor: "#2a2a2a",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  closeButton: {
    alignSelf: "flex-end",
    padding: 16,
  },
  menuItem: {
    paddingVertical: 18,
    paddingHorizontal: 24,
  },
  menuText: {
    color: "white",
    fontSize: 17,
  },
  shareModalContainer: {
    flex: 1,
    backgroundColor: "#1e1e1e",
  },
  shareModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#1a1a1a",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
    minHeight: 60,
  },
  shareModalTitle: {
    color: "white",
    fontSize: 20,
    fontWeight: "600",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 16,
  },
  closeShareButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  qrContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  linkContainer: {
    paddingHorizontal: 24,
    paddingBottom: 60,
  },
  linkBox: {
    backgroundColor: "#2a2a2a",
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#333",
  },
  linkText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
    fontFamily: "monospace",
  },
  shareInstructions: {
    color: "#aaa",
    fontSize: 16,
    textAlign: "center",
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "#1e1e1e",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#1a1a1a",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
    minHeight: 60,
  },
  modalTitle: {
    color: "white",
    fontSize: 20,
    fontWeight: "600",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 16,
  },
  closeModalButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  searchContainer: {
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    backgroundColor: "#2a2a2a",
    color: "white",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 16,
    fontSize: 17,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#333",
  },
  searchButton: {
    backgroundColor: PRIMARY_APP_COLOR,
    padding: 16,
    borderRadius: 16,
    minWidth: 56,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  loadingText: {
    color: "#aaa",
    fontSize: 17,
    marginTop: 16,
  },
  userItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
    minHeight: 80,
  },
  userInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  userAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 16,
  },
  userAvatarPlaceholder: {
    backgroundColor: PRIMARY_APP_COLOR,
    justifyContent: "center",
    alignItems: "center",
  },
  userAvatarText: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
  },
  userName: {
    color: "white",
    fontSize: 17,
    fontWeight: "500",
    marginBottom: 2,
  },
  userUsername: {
    color: "#aaa",
    fontSize: 15,
  },
  inviteButton: {
    backgroundColor: PRIMARY_APP_COLOR,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    minWidth: 80,
    alignItems: "center",
  },
  inviteButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "500",
  },
  routeItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
    minHeight: 80,
  },
  routeInfo: {
    flex: 1,
    paddingRight: 16,
  },
  routeItemName: {
    color: "white",
    fontSize: 17,
    fontWeight: "500",
    marginBottom: 4,
  },
  routeItemDetail: {
    color: "#aaa",
    fontSize: 15,
    lineHeight: 20,
  },
  addButton: {
    backgroundColor: PRIMARY_APP_COLOR,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    minWidth: 80,
    alignItems: "center",
  },
  addButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "500",
  },
  emptyResults: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  emptyResultsText: {
    color: "#aaa",
    fontSize: 20,
    fontWeight: "500",
    marginBottom: 12,
    textAlign: "center",
  },
  emptyResultsSubtext: {
    color: "#666",
    fontSize: 16,
    textAlign: "center",
    lineHeight: 24,
  },
})
